version: "3"

services:
  event-service:
    container_name: event-service
    restart: always
    build: ./hydra-event-service
    ports:
      - 8001:8000
    environment:
      - POSTGRES_HOST=postgres-event-service
      - POSTGRES_DB=event_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - AUTH_SERVICE_URL="http://0.0.0.0:8080"
    depends_on:
      - postgres-event-service
    develop:
      watch:
      - action: sync
        path: ./hydra-event-service
        target: .

  postgres-event-service:
    container_name: postgres-event-service
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./hydra-event-service/dumps/main.sql:/docker-entrypoint-initdb.d/main.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=event_service
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust


  auth-service:
    container_name: auth-service
    restart: always
    build: ./hydra-auth-service
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth-service:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DIALECT=postgresql
    depends_on:
      - postgres-auth-service

  postgres-auth-service:
    container_name: db
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
    data:
        driver: local