name: deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      
      - name: 🚀 Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USR}}
          password: ${{secrets.PASS}}
          port: 22
          script: |
            cd /home/poslam/portal
            git pull
            make update